# DO NOT USE
# Used to surface liquibase direct from dockerhub for depndabot to notify us of updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
# Why we need this: https://zendesk.atlassian.net/browse/PCCHISTORY-180

# liquibase
FROM liquibase/liquibase:4.16.1
# ubuntu-20.04
COPY --from=713408432298.dkr.ecr.us-west-2.amazonaws.com/base/zendesk/docker-images-base/ubuntu:focal /usr/local/bin/dumb-init /usr/local/bin/wait_for_envoy /usr/local/bin

ENTRYPOINT ["dumb-init", "wait_for_envoy"]
USER 1000
CMD ["/bin/echo", "'Do not use this Dockerfile!'"]
